# Generated by Django 4.2.3 on 2023-08-12 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_especialistaprofile_especialidades'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='segundo_nombre',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='direccion',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='nacionalidad',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='rut',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('NB', 'No Binario'), ('NO', 'Prefiero no Decirlo')], max_length=2),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='telefono',
            field=models.CharField(max_length=20),
        ),
    ]
