# Generated by Django 4.2.3 on 2023-07-17 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_alter_cita_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='estado',
            field=models.CharField(choices=[('RE', 'Reservada'), ('TE', 'Terminada'), ('AN', 'Anulada'), ('PA', 'Pagada')], default='RE', max_length=2),
        ),
        migrations.AlterField(
            model_name='cita',
            name='motivo',
            field=models.TextField(blank=True),
        ),
    ]
