# Generated by Django 4.2.3 on 2023-07-17 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_alter_cita_estado_alter_cita_motivo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='nacionalidad',
        ),
    ]
