# Generated by Django 4.2.3 on 2023-07-19 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_remove_cliente_nacionalidad'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='primero_apellido',
            new_name='primer_apellido',
        ),
    ]
