# Generated by Django 4.2.3 on 2023-07-25 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_especialistaprofile_especialidades'),
        ('booking', '0008_rename_primero_apellido_cliente_primer_apellido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='especialista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='accounts.especialistaprofile'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('NB', 'No Binario'), ('NO', 'Prefiero no Decirlo')], max_length=2),
        ),
    ]
