# Generated by Django 4.2.3 on 2023-08-02 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_alter_cita_estado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cita',
            options={'ordering': ('cliente__nombre',), 'verbose_name': 'Cita', 'verbose_name_plural': 'Citas'},
        ),
        migrations.AlterField(
            model_name='cita',
            name='estado',
            field=models.CharField(choices=[('RS', 'Reservada'), ('CF', 'Confirmada'), ('RL', 'Realizada'), ('AN', 'Anulada'), ('PA', 'Pagada')], default='RS', max_length=2),
        ),
        migrations.AlterField(
            model_name='cita',
            name='motivo',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('total', models.PositiveIntegerField(default=0)),
                ('folio', models.CharField(blank=True, max_length=20)),
                ('cod_especialista', models.CharField(max_length=20)),
                ('metodo', models.CharField(choices=[('TA', 'Tarjeta'), ('EF', 'Efectivo'), ('FO', 'Fonasa'), ('IS', 'Isapre'), ('CO', 'Convenio')], max_length=2)),
                ('cita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Pagos', to='booking.cita')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
            },
        ),
        migrations.CreateModel(
            name='HistorialAnulacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField()),
                ('cita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historiales_anulacion', to='booking.cita')),
            ],
            options={
                'verbose_name': 'HistorialAnulacion',
                'verbose_name_plural': 'HistorialAnulaciones',
            },
        ),
    ]
