# Generated by Django 4.2.3 on 2023-08-04 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_alter_cita_options_alter_cita_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='folio',
            field=models.CharField(default='Sin Folio', max_length=20),
        ),
    ]
