# Generated by Django 4.2.3 on 2023-08-04 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0012_alter_pago_folio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='folio',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
