# Generated by Django 4.2.3 on 2023-08-09 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0013_alter_pago_folio'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='obs',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='cita',
            name='realizada',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cita',
            name='estado',
            field=models.CharField(choices=[('RS', 'Reservada'), ('CF', 'Confirmada'), ('AN', 'Anulada'), ('PA', 'Pagada')], default='RS', max_length=2),
        ),
    ]
