# Generated by Django 4.2.3 on 2023-08-09 16:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0014_cita_obs_cita_realizada_alter_cita_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 8, 9, 16, 30, 10, 343539, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cita',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cita',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='historialanulacion',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 8, 9, 16, 30, 17, 355688, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historialanulacion',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='historialanulacion',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
