# Generated by Django 4.2.3 on 2023-08-10 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0015_cita_created_cita_is_active_cita_modified_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'permissions': [('can_add_new_cliente', 'can add new cliente')], 'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
    ]
