# Generated by Django 4.2.3 on 2023-10-31 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0018_cliente_created_cliente_is_active_cliente_modified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='numero_cita',
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
